# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 19:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1024)),
                ('comment_type', models.SmallIntegerField(choices=[(0, '评论'), (1, '讲师回复'), (2, '官方客服')], default=0, verbose_name='评论类型')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('p_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Comment', verbose_name='父级评论')),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterModelTable(
            name='tag',
            table='api_tag',
        ),
    ]
