# Generated by Django 2.1.3 on 2019-02-27 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2G',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('boys', models.ManyToManyField(through='app02.B2G', to='app02.Boy')),
            ],
        ),
        migrations.AddField(
            model_name='b2g',
            name='boy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.Boy'),
        ),
        migrations.AddField(
            model_name='b2g',
            name='girl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.Girl'),
        ),
    ]
