# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-11 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
