# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-11 01:27
from __future__ import unicode_literals

import app01.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20181011_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=app01.models.MyCharField(default='12345678901', max_length=11),
            preserve_default=False,
        ),
    ]
