# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-11 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_column='myname', max_length=32),
        ),
    ]
