# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-11 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20181011_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[(1, '男'), (2, '女')], default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_column='myname', max_length=32, verbose_name='姓名'),
        ),
    ]
