# Generated by Django 2.1.3 on 2019-02-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_auto_20190227_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
    ]
