# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-05 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20181105_1146'),
        ('crm', '0002_auto_20181105_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.User'),
        ),
    ]
